Feature/006 - Tela de lista de agendamentos
nextinhuh/clinic-system pull request #4
Opened 2024-05-03 12:48 UTC by Mevzin

2024-05-03 12:48 UTC, Mevzin commented
![](https://github.trello.services/images/mini-trello-icon.png) [[006] [FRONT] Criar página para a funcionalidade de AGENDAMENTO](https://trello.com/c/wnrKyzdQ/7-006-front-criar-p%C3%A1gina-para-a-funcionalidade-de-agendamento)

2024-05-04 23:04 UTC, nextinhuh requested changes

2024-05-04 23:04 UTC, nextinhuh commented on src/components/app-layout/components/NavMenu.tsx
>          CONSULTAS
Faltou remover o menu de consultas

2024-05-04 23:04 UTC, nextinhuh commented on src/components/form-controller/index.tsx
> +                <SelectItem key={option.id} value={option.id}>
nesse caso, é uma boa prática, colocar além do valor por exemplo do id, concatenar com o index do map, fica assim:

(option, index) => (
key={option.id + index}
)

2024-05-04 23:04 UTC, nextinhuh commented on src/components/form-controller/index.tsx
> +  type: string | undefined,
uma coisa que falou eu fazer, foi colocar a typagem de todos os tipos que são aceitos no component "<Input />" pra ficar um autocomplete certinho, sabe ?

2024-05-04 23:04 UTC, nextinhuh commented on src/routes/patient.routes.tsx
> +    path: 'schedule',
mantém o padrão, e coloca o "/" antes do nome do path por favor, só pra manter o padrão mesmo

2024-05-04 23:04 UTC, nextinhuh commented on src/utils/schemas.ts
> +// ANAMNESIS
remover coméntario

2024-05-04 23:04 UTC, nextinhuh commented on src/utils/schemas.ts
> +// SCHEDULE
remover coméntario

2024-05-04 23:04 UTC, nextinhuh commented on src/utils/schemas.ts
> +      endDate: z.coerce.date(),
no caso não era para precisar desse campo, porque você não precisa de um dataRange, e sim de um datePicker normal, para selecionar apenas 1 data

2024-05-07 16:28 UTC, Mevzin reviewed
Finished changes

2024-05-07 16:50 UTC, nextinhuh approved these changes

2024-05-07 16:50 UTC, merged