[Feature/007] - Criar componente para criar um novo agendamento
nextinhuh/clinic-system pull request #5
Opened 2024-05-08 19:10 UTC by Mevzin

✔ Modal criado
✔ Campos sendo validados
✔ Campo data so passa sendo um dia a frente da data atual
✔ Lista de paciente sendo mostrada e pegando os pacientes cadastrados
✔ Salvar no banco com seus respectivos dados

2024-05-08 19:12 UTC, Mevzin commented
![](https://github.trello.services/images/mini-trello-icon.png) [[007] [FRONT] Criar componente para criar um novo agendamento](https://trello.com/c/A7Zuiblg/8-007-front-criar-componente-para-criar-um-novo-agendamento)

2024-05-21 02:55 UTC, nextinhuh requested changes

2024-05-21 02:55 UTC, nextinhuh commented on src/pages/schedule/create-schedule-dialog/index.tsx
> +            // @ts-expect-error Type option
precisa retirar esse comentário, não pode existir furo na tipagem

2024-05-21 02:55 UTC, nextinhuh commented on src/service/patient.service.ts
> +const SCHEDULES_FIRESTORE_KEY = 'schedules'
tem que criar um service para cada key, essa a intenção de se existir uma KEY

2024-05-21 02:55 UTC, nextinhuh commented on src/components/form-controller/index.tsx
> +    case 'calendar':
precisa resolver um problema de espaçamento, de uma forma que fique no mesmo padrão: 

Label + Input

igual nos outros casos do formBuilder, no caso do calendário a label ta ficando na mesma linha do input, não pode

2024-05-21 02:55 UTC, nextinhuh commented on src/components/form-controller/index.tsx
> +                  format(field.value, 'PPP')
usar o "locale" do date-fns para formatar no padrão brasileiro

obs: depois pensar numa forma de deixar configuração o locale global por exemplo no arquivo main, para não precisar ficar setando em cada canto que usar o date-fns

2024-05-21 02:55 UTC, nextinhuh commented on src/pages/schedule/create-schedule-dialog/index.tsx
> +      options: allPatients,
tem que ajeitar a regra de negócio, esta vindo todos os pacientes independente do usuário logado, na regra de negócio não esta assim

2024-05-21 02:55 UTC, nextinhuh commented on src/pages/schedule/create-schedule-dialog/index.tsx
> +      })
faltou colocar a regra para fechar o modal após a requisição der certo

2024-05-21 14:19 UTC, Mevzin reviewed
Changes finished

2024-05-21 15:02 UTC, nextinhuh approved these changes

2024-05-21 15:02 UTC, merged